### ISSUE TITLE
Updating dependencies fails

### ISSUE THREAD

**Issue by Evil-Devil** [claranet/spryker-demoshop#8]
Hi,
as the title implies updating dependencies fails for me. I'm not sure why, because I haven't done anything special in particular.

Message output:

> $ docker/run devel update-deps
Updating dependencies in running container ...
Entering Yves container ...
Executing: docker-compose -f docker-compose-devel.yml -p spryker_devel exec yves /entrypoint.sh build-deps
WARNING: The NETRC variable is not set. Defaulting to a blank string.
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"C:/Users/benjamin.behrendt/AppData/Local/Programs/Git/entrypoint.sh\": stat C:/Users/benjamin.behrendt/AppData/Local/Programs/Git/entrypoint.sh: no such file or directory"

> Entering Yves container ...
Executing: docker-compose -f docker-compose-devel.yml -p spryker_devel exec zed /entrypoint.sh build-deps
WARNING: The NETRC variable is not set. Defaulting to a blank string.
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"C:/Users/benjamin.behrendt/AppData/Local/Programs/Git/entrypoint.sh\": stat C:/Users/benjamin.behrendt/AppData/Local/Programs/Git/entrypoint.sh: no such file or directory

Any idea what might be wrong?

I already thought of installing composer and npm directly in the containers to have full control over the environment ...

**Comment by fuhbar** [comment]
Hi @Evil-Devil, 

this error seems to be interesting. We are actually using Linux and MacOS and these are the only platforms we are currently developing on and testing against. 

What you have quoted seems to be some error which occurs while entering the container via `docker-compose`. So please try to manually entering the container via either:

* `./docker/run devel enter yves` or
* `docker-compose -f docker-compose-devel.yml -p spryker_devel exec yves  /bin/sh`  or
* `docker exec -it $(docker ps -q -f name=yves -l) /bin/sh`

If exec-ing into the container is not the actual problem, which the error message suggests, than we need to investigate, why docker thinks that `/entrypoint.sh` of the container is to be found outside within your host system under `C:/Users/benjamin.behrendt/AppData/Local/Programs/Git`. Do you have any idea, why the docker daemon takes this path into consideration? Is this some shared path between your host system and your docker VM?

**Comment by Evil-Devil** [comment]
None of the above works. To enter the container I need to use `docker exec -ti sprykerdevel_yves_1 sh`

According to my google searches it might be an issue with Gitbash and mingw in switching from root to local directory to resolve pathes. Pretty weird. For the moment I'll create the container image with dev-tools available and hopefully find out meanwhile how to solve this issue.

**Comment by Evil-Devil** [comment]
Will close it. Docker for windows is negletable.
